### ISSUE TITLE
NullReferenceException when opening a soft-deleted stream

### ISSUE THREAD

**Issue by iblazhko** [BullOak/BullOak.Repositories.EventStore#18]
`BeginSessionFor` fails with `NullReferenceException` when attempting to open a stream that has been soft deleted.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at BullOak.Repositories.EventStore.Events.EventConversion.ToItemWithType(ResolvedEvent resolvedEvent, ICreateStateInstances stateFactory)
   at BullOak.Repositories.EventStore.Streams.EventReader.<>c__DisplayClass3_0.<ReadFrom>b__0(ResolvedEvent x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at BullOak.Repositories.EventStore.Streams.EventReader.ReadFrom(IStreamReaderStrategy streamReaderStrategy, Nullable`1 appliesAt)
   at BullOak.Repositories.EventStore.EventStoreSession`1.Initialize(Nullable`1 appliesAt)
   at BullOak.Repositories.EventStore.EventStoreRepository`2.BeginSessionFor(TId id, Boolean throwIfNotExists, Nullable`1 appliesAt)
```

Steps to reproduce:

1. Create a stream and populate it with some events, e.g. by `session = await repository.BeginSessionFor(...); session.AddEvents(...); await session.SaveChanges();` 
2. Delete stream using EventStore management interface or by using HTTP `DELETE /streams/{streamId}`
3. Try to use `session = await repository.BeginSessionFor(...);` for the same stream id

**Comment by iblazhko** [comment]
There is a test that should cover this: https://github.com/BullOak/BullOak.Repositories.EventStore/blob/06ebbd90f7b3b35991e0fa6b278d15f090f118e5/src/BullOak.Repositories.EventStore.Test.Integration/Specification/ReconstituteState.feature#L45

`I soft-delete the stream` step deletes the stream using `connection.DeleteStreamAsync`: https://github.com/BullOak/BullOak.Repositories.EventStore/blob/06ebbd90f7b3b35991e0fa6b278d15f090f118e5/src/BullOak.Repositories.EventStore/EventstoreRepository.cs#L93

~~However it looks like that test does not actually commit changes to EventStore when creating the stream.~~

**Comment by iblazhko** [comment]
Local debugging shows that in `EventConversion.ReadTypeFromMetadata` https://github.com/BullOak/BullOak.Repositories.EventStore/blob/06ebbd90f7b3b35991e0fa6b278d15f090f118e5/src/BullOak.Repositories.EventStore/Events/EventConversion.cs#L39
`ResolvedEvent` has `EventType` value `$metadata`.

`Type.GetType` https://github.com/BullOak/BullOak.Repositories.EventStore/blob/06ebbd90f7b3b35991e0fa6b278d15f090f118e5/src/BullOak.Repositories.EventStore/Events/EventConversion.cs#L46 does not throw, but returns `null` instance that gets propagated to the caller and it eventually throws in `ToItemWithType` at `if (type.IsInterface)` https://github.com/BullOak/BullOak.Repositories.EventStore/blob/06ebbd90f7b3b35991e0fa6b278d15f090f118e5/src/BullOak.Repositories.EventStore/Events/EventConversion.cs#L20

Still no idea why this error does not appear in integration tests.

**Comment by iblazhko** [comment]
Changes from https://github.com/BullOak/BullOak.Repositories.EventStore/pull/20 allowed me to open soft-deleted stream locally, but unfortunately it also breaks some integration tests and CI build fails.

**Comment by iblazhko** [comment]
This problem is essentially https://github.com/BullOak/BullOak.Repositories.EventStore/issues/9 but with more context of how to reproduce.

**Comment by skleanthous** [comment]
Done
